### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sethb3744** [linnarsson-lab/pysmFISH#2]
Hi,
I ran into an issue while installing pysmFISH. I am using Linux with CentOS. I first tried using "pip install --no-cache-dir pysmFISH", and then tried git clone then "pip install -e .", but both showed the same error. The error message by itself is below, followed by the entire log after I ran "pip install -e ." 
Thanks,
Seth

Collecting loompy (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/18/38/6231e36536a3741e2cc10fada493b8f1d900a57f13f6b416528a195fc601/loompy-2.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RHRS4e/loompy/setup.py", line 26
        download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",
                                                                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-RHRS4e/loompy/

[sethberg@iq218 pysmFISH]$ pip install -e .
Obtaining file:///netapp/home/sethberg/dependencies/pysmFISH
Requirement already satisfied: numpy in /netapp/home/sethberg/dependencies/Python-2.7.15/lib/python2.7/site-packages (from pysmFISH==0.1.5) (1.15.0)
Requirement already satisfied: scipy in /netapp/home/sethberg/dependencies/Python-2.7.15/lib/python2.7/site-packages (from pysmFISH==0.1.5) (1.1.0)
Collecting scikit-image (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/b7/f2/86276b010ab3bbd253eca58c1be4c6eb2440977854fd303b673ea080979f/scikit_image-0.14.1-cp27-cp27m-manylinux1_x86_64.whl
Collecting scikit-learn (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/c3/23/8998fab022eba618732438ff25b8da506a75758ccc27a570cf8016434a14/scikit_learn-0.20.1-cp27-cp27m-manylinux1_x86_64.whl
Requirement already satisfied: matplotlib in /netapp/home/sethberg/dependencies/Python-2.7.15/lib/python2.7/site-packages (from pysmFISH==0.1.5) (2.2.3)
Collecting nd2reader==2.1.3 (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/eb/a6/33422382a42c2af075c0173dded88442d482640b213b7868a832917cc0c4/nd2reader-2.1.3.tar.gz
Collecting sympy (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/dd/f6/ed485ff22efdd7b371d0dbbf6d77ad61c3b3b7e0815a83c89cbb38ce35de/sympy-1.3.tar.gz
Collecting ruamel.yaml (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/00/03/1ba00c7943607f062a42bda9fcab4c14f3db745f0b5a88ad97891583d962/ruamel.yaml-0.15.81-cp27-cp27m-manylinux1_x86_64.whl
Collecting h5py (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/9a/2c/d84c232fd29db708062afd068032e4863dfbdc1fa9fe8f82b4413d3cbfc4/h5py-2.8.0-cp27-cp27m-manylinux1_x86_64.whl
Collecting dask (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/b4/e5/6407c2349622699eab0881e6bc6e978b8da67872a105e5e20b72ff190c65/dask-1.0.0-py2.py3-none-any.whl
Collecting distributed (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/be/03/077a70195a178319f615119b3b02294fc982fa4e3e99f3e853c8fd82a8f0/distributed-1.25.1-py2.py3-none-any.whl
Collecting mpi4py (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/31/27/1288918ac230cc9abc0da17d84d66f3db477757d90b3d6b070d709391a15/mpi4py-3.0.0.tar.gz
Requirement already satisfied: cython in /netapp/home/sethberg/dependencies/Python-2.7.15/lib/python2.7/site-packages (from pysmFISH==0.1.5) (0.28.5)
Collecting loompy (from pysmFISH==0.1.5)
  Using cached https://files.pythonhosted.org/packages/18/38/6231e36536a3741e2cc10fada493b8f1d900a57f13f6b416528a195fc601/loompy-2.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RHRS4e/loompy/setup.py", line 26
        download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz",
                                                                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-RHRS4e/loompy/

**Comment by simone-codeluppi** [comment]
Hi
it maybe something that has to do with the version of python installed. Loompy requires python 3.6 or later (http://linnarssonlab.org/loompy/installation/index.html).

**Comment by sethb3744** [comment]
Hi,

My issue was solved after I installed miniconda3 and used pip from that program instead. For some reason, the pip from my installation of Python 3.7.2 alone was not working properly.

Best,
Seth
